#!/usr/bin/env bash
# a bash script to transfer a file from our client to a server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_to_file=$1
ip=$2
username=$3
path_to_key=$4

scp -o "StrictHostKeyChecking no" -i "$path_to_key" "$path_to_file" "$username@$ip:~/"

if [ $? -eq 0 ]
then
  echo "FILE TRANSFER WAS SUCCESSFULL"
else
  echo "FILE TRANSFER FAILED"
fi
