#!/usr/bin/env bash
# install Nginx on a Web Sever

# Updating Packages
sudo apt-get update
sudo apt-get -y install nginx

# Allow incoming traffic
sudo ufw allow 'Nginx HTTP'

# create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations (Syntax errors)
sudo nginx -t
sudo service nginx start
