#!/usr/bin/env bash
# a script for the installation and setup of HAProxy
# on the server named lb-01.
# Configure HAProxy to route traffic to servers web-01 and web-02.
#Employ a roundrobin  algorithm for distributing requests.
#Ensure that HAProxy can be administered via an initialization script

sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo touch /etc/haproxy/haproxy.cfg

# Build the HAProxy configuration file
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 34.239.207.113:80 check
    server web-02 54.237.85.74:80 check
EOT

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
