#!/usr/bin/env bash
# displays the time of 12 HH and 59 MM.

HH=0
while [ $HH -lt 13 ]
do
    echo "Hour: $HH"
    MM=1
    while [ $MM -lt 60 ]
    do
        echo $MM
	let MM+=1
    done
    let HH+=1
done
